# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=18, max_digits=18)),
                ('longitude', models.DecimalField(decimal_places=18, max_digits=18)),
                ('elevation', models.DecimalField(decimal_places=18, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='begin', to='tracking.Position')),
                ('end', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='end', to='tracking.Position')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=10)),
                ('descr', models.CharField(max_length=200)),
                ('tracks', models.ManyToManyField(to='tracking.Segment')),
            ],
        ),
    ]
