# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.CharField(max_length=40)),
                ('longitude', models.CharField(max_length=40)),
                ('elevation', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('begin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='begin', to='tracking.Position')),
                ('end', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='end', to='tracking.Position')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, unique=True)),
                ('descr', models.CharField(max_length=200)),
                ('tracks', models.ManyToManyField(to='tracking.Segment')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together=set([('latitude', 'longitude', 'elevation')]),
        ),
        migrations.AlterUniqueTogether(
            name='segment',
            unique_together=set([('begin', 'end')]),
        ),
    ]
